image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - nim
  - nimble
  - pcre
tasks:
  - test: |
      cd xidoc
      nimble test -y
  - upload: |
      if test "$(git -C xidoc rev-parse HEAD)" = "$(git -C xidoc rev-parse master)"; then
        tar -cvzC xidoc/site . -f site.tar.gz
        hut pages publish -d xidoc.nim.town site.tar.gz
      fi
