image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
tasks:
  - package: |
      cd xidoc/docs
      tar -cvz . > ../../site.tar.gz
  - upload: |
      hut pages publish -d xidoc.nim.town site.tar.gz
