image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
tasks:
  - package: |
      cd xidoc/docs
      tar -cvz . > ../../site.tar.gz
  - upload: |
      hut pages publish -d xigoi.srht.site -s xidoc site.tar.gz
